import ROOT
ROOT.gSystem.Load("rootlogon_C.so")
ROOT.rootlogon()
#ROOT.gROOT.SetBatch(ROOT.kTRUE) #Do not show-up canvases

file=ROOT.TFile('data_file.root','READ')
tree=file.Get("data_tree")

c1=ROOT.TCanvas()
h=ROOT.TH1F("h","h",250,0,5000)
tree.Draw("actual>>h")
h.GetXaxis().SetTitle("actual [kW]")
h.GetYaxis().SetTitle("number of events")
c1.SaveAs("Plots/actual.png")

#c1_1=ROOT.TCanvas()
#tree.Draw("date[2]")
#c1_1.SaveAs("Plots/days.png")

c2=ROOT.TCanvas()
h0=ROOT.TH1F("h0","h0",90,0,30)
tree.Draw("speed[0]>>h0")
h1=ROOT.TH1F("h1","h1",90,0,30)
tree.Draw("speed[1]>>h1")
h2=ROOT.TH1F("h2","h2",90,0,30)
tree.Draw("speed[2]>>h2")
h3=ROOT.TH1F("h3","h3",90,0,30)
tree.Draw("speed[3]>>h3")
h0.SetMaximum(1500)
h0.SetLineColor(ROOT.kBlue)
h0.GetYaxis().SetTitle("number of events")
h0.GetXaxis().SetTitle("speed [m/s]")
h0.Draw()
h1.SetLineColor(ROOT.kRed)
h1.Draw("same")
h2.SetLineColor(ROOT.kGreen)
h2.Draw("same")
h3.SetLineColor(ROOT.kBlack)
h3.Draw("same")
leg=ROOT.TLegend(0.6,0.6,0.82,0.82)
leg.AddEntry(h0,"pt 1","l")
leg.AddEntry(h1,"pt 2","l")
leg.AddEntry(h2,"pt 3","l")
leg.AddEntry(h3,"pt 4","l")
leg.Draw("same")
c2.SaveAs("Plots/speeds.png")

c3=ROOT.TCanvas()
dir0=ROOT.TH1F("dir0","dir0",360,0,360)
tree.Draw("direction[0]>>dir0")
dir1=ROOT.TH1F("dir1","dir1",360,0,360)
tree.Draw("direction[1]>>dir1")
dir2=ROOT.TH1F("dir2","dir2",360,0,360)
tree.Draw("direction[2]>>dir2")
dir3=ROOT.TH1F("dir3","dir3",360,0,360)
tree.Draw("direction[3]>>dir3")
dir0.GetXaxis().SetTitle("direction [degree]")
dir0.GetYaxis().SetTitle("number of events")
dir0.SetLineColor(ROOT.kBlue)
dir0.Draw()
dir1.SetLineColor(ROOT.kRed)
dir1.Draw("same")
dir2.SetLineColor(ROOT.kGreen)
dir2.Draw("same")
dir3.SetLineColor(ROOT.kBlack)
dir3.Draw("same")
leg.Draw("same")
c3.SaveAs("Plots/directions.png")

